import AppKit
import ApplicationServices
import Foundation

/// Delivers a transcript into the user's focused field.
///
/// Primary path matches VoiceInk `CursorPaster` and Handy: clipboard + Cmd+V.
/// We deliberately do **not** trust AX `kAXSelectedText` success alone  -  Electron
/// apps (Cursor, T3 Code, VS Code, Slack, …) often report success while the
/// webview never receives the text, which made history say "Pasted" with an
/// empty field.
@MainActor
final class TextDeliveryService {
  private let markerType = NSPasteboard.PasteboardType(
    "ca.hankyone.ListenToMe.PasteSession"
  )

  /// Conventions used by Maccy/Paste/etc. so clipboard managers skip the
  /// transient paste payload (same approach as Handy).
  private let concealmentTypes: [NSPasteboard.PasteboardType] = [
    NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
    NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
    NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
  ]

  func deliver(
    _ text: String,
    to target: TargetApplication?
  ) async -> DeliveryOutcome {
    // Always leave the transcript on the clipboard. Restoring the previous
    // pasteboard races apps that paste asynchronously (Handy #502).
    copy(text)

    let trusted = PermissionService.isAccessibilityTrusted()
    let attempt = DeliveryPolicy.canAttemptPaste(
      target: target,
      hasAccessibilityPermission: trusted
    )
    guard attempt == .pasted, let target else {
      return attempt
    }

    // Bring the original app forward before synthesizing keys.
    _ = activate(target)
    try? await Task.sleep(nanoseconds: 100_000_000)
    for _ in 0..<5 {
      let frontmostPID = NSWorkspace.shared.frontmostApplication?.processIdentifier
      if frontmostPID == target.processIdentifier { break }
      _ = activate(target)
      try? await Task.sleep(nanoseconds: 60_000_000)
    }

    let frontmostPID = NSWorkspace.shared.frontmostApplication?.processIdentifier
    let focusOK =
      DeliveryPolicy.outcome(
        target: target,
        frontmostProcessIdentifier: frontmostPID,
        hasAccessibilityPermission: true
      ) == .pasted

    if !focusOK {
      return .copiedFocusChanged
    }

    let marker = UUID().uuidString
    guard preparePasteboard(text: text, marker: marker) else {
      copy(text)
      return .copiedPasteFailed
    }

    // VoiceInk pre-paste settle  -  Electron needs a beat after activate().
    let settleNs: UInt64 =
      isChromiumHost(target) || isTerminalHost(target) ? 180_000_000 : 100_000_000
    try? await Task.sleep(nanoseconds: settleNs)

    // Cmd+V is the real delivery path (VoiceInk CursorPaster). Always attempt
    // it  -  never trust AX selectedText success on Electron first.
    // GPU terminals (Ghostty, kitty, …) often ignore HID Cmd+V; System Events
    // keystrokes land in the shell when HID does not.
    var pasted = false
    if isTerminalHost(target) {
      pasted = pasteViaAppleScriptKeyCode()
      if !pasted {
        pasted = pasteViaEditMenu()
      }
      if !pasted {
        pasted = await postPasteShortcut()
      }
    } else {
      pasted = await postPasteShortcut()
      if !pasted {
        pasted = pasteViaAppleScriptKeyCode()
      }
      if !pasted {
        pasted = pasteViaEditMenu()
      }
    }

    // Native AX insert only as a last resort, and only when we can verify the
    // value actually contains our text (Electron lies about selectedText).
    if !pasted {
      pasted = insertTextViaAccessibilityVerified(text)
    }

    return pasted ? .pasted : .copiedPasteFailed
  }

  func copy(_ text: String) {
    let pasteboard = NSPasteboard.general
    pasteboard.clearContents()
    pasteboard.setString(text, forType: .string)
  }

  private func activate(_ target: TargetApplication) -> Bool {
    guard
      let app = NSRunningApplication(processIdentifier: target.processIdentifier)
    else {
      return false
    }
    if #available(macOS 14.0, *) {
      NSApp.yieldActivation(to: app)
    }
    return app.activate()
  }

  private func isTerminalHost(_ target: TargetApplication) -> Bool {
    let id = (target.bundleIdentifier ?? "").lowercased()
    let name = target.name.lowercased()
    let needles = [
      "ghostty", "iterm", "terminal", "kitty", "alacritty", "warp", "wezterm",
    ]
    return needles.contains { id.contains($0) || name.contains($0) }
  }

  private func isChromiumHost(_ target: TargetApplication) -> Bool {
    let id = (target.bundleIdentifier ?? "").lowercased()
    let name = target.name.lowercased()
    let needles = [
      "electron", "t3", "cursor", "vscode", "code", "slack", "discord",
      "figma", "notion", "chrome", "chromium", "brave", "edge", "arc",
    ]
    return needles.contains { id.contains($0) || name.contains($0) }
  }

  private func preparePasteboard(text: String, marker: String) -> Bool {
    let pasteboard = NSPasteboard.general
    pasteboard.clearContents()
    guard pasteboard.setString(text, forType: .string) else { return false }
    _ = pasteboard.setString(marker, forType: markerType)
    for type in concealmentTypes {
      _ = pasteboard.setString("", forType: type)
    }
    return true
  }

  /// AX insert with read-back verification. Unverified success is ignored  - 
  /// that was the Electron false-positive that marked takes as Pasted.
  private func insertTextViaAccessibilityVerified(_ text: String) -> Bool {
    guard PermissionService.isAccessibilityTrusted() else { return false }

    let systemWide = AXUIElementCreateSystemWide()
    var focusedObject: CFTypeRef?
    guard
      AXUIElementCopyAttributeValue(
        systemWide,
        kAXFocusedUIElementAttribute as CFString,
        &focusedObject
      ) == .success,
      let focusedObject
    else {
      return false
    }

    let focused = focusedObject as! AXUIElement

    var settable = DarwinBoolean(false)
    if AXUIElementIsAttributeSettable(
      focused,
      kAXValueAttribute as CFString,
      &settable
    ) == .success, settable.boolValue {
      var currentObject: CFTypeRef?
      let current =
        AXUIElementCopyAttributeValue(
          focused,
          kAXValueAttribute as CFString,
          &currentObject
        ) == .success
        ? (currentObject as? String) ?? ""
        : ""
      let combined = current + text
      guard
        AXUIElementSetAttributeValue(
          focused,
          kAXValueAttribute as CFString,
          combined as CFTypeRef
        ) == .success
      else {
        return false
      }

      var verifyObject: CFTypeRef?
      guard
        AXUIElementCopyAttributeValue(
          focused,
          kAXValueAttribute as CFString,
          &verifyObject
        ) == .success,
        let verified = verifyObject as? String,
        verified.contains(text)
      else {
        return false
      }
      return true
    }

    // selectedText without verification is how Electron fooled us  -  skip it.
    return false
  }

  /// Cmd+V via CGEvent  -  VoiceInk `CursorPaster` (privateState + hid tap).
  private func postPasteShortcut() async -> Bool {
    guard PermissionService.isAccessibilityTrusted() else { return false }

    let source = CGEventSource(stateID: .privateState)
    let commandKeyCode: CGKeyCode = 0x37
    let vKeyCode: CGKeyCode = 0x09
    let gapNs: UInt64 = 10_000_000

    guard
      let cmdDown = CGEvent(
        keyboardEventSource: source,
        virtualKey: commandKeyCode,
        keyDown: true
      ),
      let vDown = CGEvent(
        keyboardEventSource: source,
        virtualKey: vKeyCode,
        keyDown: true
      ),
      let vUp = CGEvent(
        keyboardEventSource: source,
        virtualKey: vKeyCode,
        keyDown: false
      ),
      let cmdUp = CGEvent(
        keyboardEventSource: source,
        virtualKey: commandKeyCode,
        keyDown: false
      )
    else {
      return false
    }

    cmdDown.flags = .maskCommand
    vDown.flags = .maskCommand
    vUp.flags = .maskCommand

    cmdDown.post(tap: .cghidEventTap)
    try? await Task.sleep(nanoseconds: gapNs)
    vDown.post(tap: .cghidEventTap)
    try? await Task.sleep(nanoseconds: gapNs)
    vUp.post(tap: .cghidEventTap)
    try? await Task.sleep(nanoseconds: gapNs)
    cmdUp.post(tap: .cghidEventTap)
    return true
  }

  private func pasteViaAppleScriptKeyCode() -> Bool {
    let source = """
      tell application "System Events" to key code 9 using command down
      """
    var error: NSDictionary?
    guard let script = NSAppleScript(source: source) else { return false }
    script.executeAndReturnError(&error)
    return error == nil
  }

  private func pasteViaEditMenu() -> Bool {
    let source = """
      tell application "System Events"
        tell (first process whose frontmost is true)
          try
            click menu item "Paste" of menu "Edit" of menu bar 1
            return true
          on error
            return false
          end try
        end tell
      end tell
      """
    var error: NSDictionary?
    guard let script = NSAppleScript(source: source) else { return false }
    let result = script.executeAndReturnError(&error)
    return error == nil && result.booleanValue
  }
}
