import AppKit
import ApplicationServices
import Foundation

/// Delivers a transcript into the user's focused field.
///
/// Patterned after Handy (clipboard + Cmd+V), VoiceInk (`CursorPaster`), and
/// Hex (`PasteboardClient`): activate the original target, try AX insert, then
/// clipboard paste with layout-safe key codes, then AppleScript Edit → Paste.
@MainActor
final class TextDeliveryService {
  private let markerType = NSPasteboard.PasteboardType(
    "ca.hankyone.ListenToMe.PasteSession"
  )

  /// Conventions used by Maccy/Paste/etc. so clipboard managers skip the
  /// transient paste payload (same approach as Handy).
  private let concealmentTypes: [NSPasteboard.PasteboardType] = [
    NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
    NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
    NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
  ]

  func deliver(
    _ text: String,
    to target: TargetApplication?
  ) async -> DeliveryOutcome {
    // Always leave the transcript on the clipboard. Restoring the previous
    // pasteboard races apps that paste asynchronously (Handy #502) and was
    // wiping the payload before Cmd+V landed.
    copy(text)

    let trusted = PermissionService.isAccessibilityTrusted()
    let attempt = DeliveryPolicy.canAttemptPaste(
      target: target,
      hasAccessibilityPermission: trusted
    )
    guard attempt == .pasted, let target else {
      return attempt
    }

    if !activate(target) {
      // Still try paste — some hosts stay frontmost without a successful activate().
    }
    try? await Task.sleep(nanoseconds: 180_000_000)

    // Retry focus briefly; activation is often async on modern macOS.
    for _ in 0..<4 {
      let frontmostPID = NSWorkspace.shared.frontmostApplication?.processIdentifier
      if frontmostPID == target.processIdentifier { break }
      _ = activate(target)
      try? await Task.sleep(nanoseconds: 80_000_000)
    }

    let frontmostPID = NSWorkspace.shared.frontmostApplication?.processIdentifier
    let focusOK =
      DeliveryPolicy.outcome(
        target: target,
        frontmostProcessIdentifier: frontmostPID,
        hasAccessibilityPermission: true
      ) == .pasted

    // 1) Direct AX insert — no key events needed (Hex).
    if insertTextViaAccessibility(text) {
      return .pasted
    }

    if !focusOK {
      // Leave text on clipboard so the user can paste manually.
      return .copiedFocusChanged
    }

    let marker = UUID().uuidString
    guard preparePasteboard(text: text, marker: marker) else {
      copy(text)
      return .copiedPasteFailed
    }

    try? await Task.sleep(nanoseconds: 60_000_000)

    // Post Cmd+V twice with a gap — Electron/Cursor often miss the first chord.
    var pasted = await postPasteShortcut()
    if pasted {
      try? await Task.sleep(nanoseconds: 120_000_000)
    } else {
      pasted = await postPasteShortcut()
    }
    if !pasted {
      pasted = pasteViaAppleScriptKeyCode()
    }
    if !pasted {
      pasted = pasteViaEditMenu()
    }

    // Keep our text on the clipboard either way.
    return pasted ? .pasted : .copiedPasteFailed
  }

  func copy(_ text: String) {
    let pasteboard = NSPasteboard.general
    pasteboard.clearContents()
    pasteboard.setString(text, forType: .string)
  }

  private func activate(_ target: TargetApplication) -> Bool {
    guard
      let app = NSRunningApplication(processIdentifier: target.processIdentifier)
    else {
      return false
    }
    if #available(macOS 14.0, *) {
      NSApp.yieldActivation(to: app)
    }
    return app.activate()
  }

  private func preparePasteboard(text: String, marker: String) -> Bool {
    let pasteboard = NSPasteboard.general
    pasteboard.clearContents()
    guard pasteboard.setString(text, forType: .string) else { return false }
    _ = pasteboard.setString(marker, forType: markerType)
    for type in concealmentTypes {
      _ = pasteboard.setString("", forType: type)
    }
    return true
  }

  /// Insert by replacing the current selection / empty selection (Hex).
  private func insertTextViaAccessibility(_ text: String) -> Bool {
    guard PermissionService.isAccessibilityTrusted() else { return false }

    let systemWide = AXUIElementCreateSystemWide()
    var focusedObject: CFTypeRef?
    guard
      AXUIElementCopyAttributeValue(
        systemWide,
        kAXFocusedUIElementAttribute as CFString,
        &focusedObject
      ) == .success,
      let focusedObject
    else {
      return false
    }

    let focused = focusedObject as! AXUIElement

    if AXUIElementSetAttributeValue(
      focused,
      kAXSelectedTextAttribute as CFString,
      text as CFTypeRef
    ) == .success {
      return true
    }

    var settable = DarwinBoolean(false)
    if AXUIElementIsAttributeSettable(
      focused,
      kAXValueAttribute as CFString,
      &settable
    ) == .success, settable.boolValue {
      var currentObject: CFTypeRef?
      let current =
        AXUIElementCopyAttributeValue(
          focused,
          kAXValueAttribute as CFString,
          &currentObject
        ) == .success
        ? (currentObject as? String) ?? ""
        : ""
      let combined = current + text
      return AXUIElementSetAttributeValue(
        focused,
        kAXValueAttribute as CFString,
        combined as CFTypeRef
      ) == .success
    }

    return false
  }

  /// Cmd+V via CGEvent. Uses physical V key code 9 so QWERTY-⌘ layouts work
  /// (VoiceInk). Small gaps between events match VoiceInk's CursorPaster.
  private func postPasteShortcut() async -> Bool {
    guard PermissionService.isAccessibilityTrusted() else { return false }

    let source =
      CGEventSource(stateID: .combinedSessionState)
      ?? CGEventSource(stateID: .hidSystemState)
    let commandKeyCode: CGKeyCode = 0x37  // Left ⌘
    let vKeyCode: CGKeyCode = 0x09  // Physical V

    guard
      let cmdDown = CGEvent(
        keyboardEventSource: source,
        virtualKey: commandKeyCode,
        keyDown: true
      ),
      let vDown = CGEvent(
        keyboardEventSource: source,
        virtualKey: vKeyCode,
        keyDown: true
      ),
      let vUp = CGEvent(
        keyboardEventSource: source,
        virtualKey: vKeyCode,
        keyDown: false
      ),
      let cmdUp = CGEvent(
        keyboardEventSource: source,
        virtualKey: commandKeyCode,
        keyDown: false
      )
    else {
      return false
    }

    cmdDown.flags = .maskCommand
    vDown.flags = .maskCommand
    vUp.flags = .maskCommand

    for event in [cmdDown, vDown, vUp, cmdUp] {
      event.post(tap: .cghidEventTap)
      event.post(tap: .cgSessionEventTap)
      try? await Task.sleep(nanoseconds: 14_000_000)
    }
    return true
  }

  private func pasteViaAppleScriptKeyCode() -> Bool {
    let source = """
      tell application "System Events" to key code 9 using command down
      """
    var error: NSDictionary?
    guard let script = NSAppleScript(source: source) else { return false }
    script.executeAndReturnError(&error)
    return error == nil
  }

  private func pasteViaEditMenu() -> Bool {
    let source = """
      tell application "System Events"
        tell (first process whose frontmost is true)
          try
            click menu item "Paste" of menu "Edit" of menu bar 1
            return true
          on error
            return false
          end try
        end tell
      end tell
      """
    var error: NSDictionary?
    guard let script = NSAppleScript(source: source) else { return false }
    let result = script.executeAndReturnError(&error)
    return error == nil && result.booleanValue
  }
}
