import AppKit
import ApplicationServices
import Foundation

/// Delivers a transcript into the user's focused field.
///
/// Patterned after Handy (clipboard + Cmd+V), VoiceInk (`CursorPaster`), and
/// Hex (`PasteboardClient`): activate the original target, try AX insert, then
/// clipboard paste with layout-safe key codes, then AppleScript Edit → Paste.
@MainActor
final class TextDeliveryService {
  private struct ClipboardSnapshot {
    let items: [[NSPasteboard.PasteboardType: Data]]
  }

  private let markerType = NSPasteboard.PasteboardType(
    "ca.hankyone.ListenToMe.PasteSession"
  )

  /// Conventions used by Maccy/Paste/etc. so clipboard managers skip the
  /// transient paste payload (same approach as Handy).
  private let concealmentTypes: [NSPasteboard.PasteboardType] = [
    NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
    NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
    NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
  ]

  func deliver(
    _ text: String,
    to target: TargetApplication?
  ) async -> DeliveryOutcome {
    // Always park the transcript on the clipboard as a safety net.
    copy(text)

    let attempt = DeliveryPolicy.canAttemptPaste(
      target: target,
      hasAccessibilityPermission: AXIsProcessTrusted()
    )
    guard attempt == .pasted, let target else {
      return attempt
    }

    // Bring the original app back before injecting keys (VoiceInk/Handy assume
    // the user's field is frontmost; finishing can leave focus elsewhere).
    if !activate(target) {
      return .copiedFocusChanged
    }
    try? await Task.sleep(nanoseconds: 120_000_000)

    let frontmostPID = NSWorkspace.shared.frontmostApplication?.processIdentifier
    guard
      DeliveryPolicy.outcome(
        target: target,
        frontmostProcessIdentifier: frontmostPID,
        hasAccessibilityPermission: true
      ) == .pasted
    else {
      return .copiedFocusChanged
    }

    // 1) Direct AX insert — no clipboard race (Hex strategy).
    if insertTextViaAccessibility(text) {
      return .pasted
    }

    // 2) Clipboard + Cmd+V, then AppleScript paste as fallback.
    let snapshot = captureClipboard()
    let marker = UUID().uuidString
    guard preparePasteboard(text: text, marker: marker) else {
      copy(text)
      return .copiedPasteFailed
    }
    let publishedChangeCount = NSPasteboard.general.changeCount

    // Brief settle so the pasteboard commit is visible (Hex waits for changeCount).
    try? await Task.sleep(nanoseconds: 80_000_000)

    let pasted =
      await postPasteShortcut()
      || pasteViaAppleScriptKeyCode()
      || pasteViaEditMenu()

    // Give slow targets time to read before restore (Handy #502 race).
    try? await Task.sleep(nanoseconds: 550_000_000)

    let stillOurs =
      NSPasteboard.general.string(forType: markerType) == marker
      && NSPasteboard.general.changeCount == publishedChangeCount

    if stillOurs {
      restoreClipboard(snapshot)
    } else if NSPasteboard.general.string(forType: .string) != text {
      // Someone else replaced the board without our text — put it back.
      copy(text)
    }

    return pasted ? .pasted : .copiedPasteFailed
  }

  func copy(_ text: String) {
    let pasteboard = NSPasteboard.general
    pasteboard.clearContents()
    pasteboard.setString(text, forType: .string)
  }

  private func activate(_ target: TargetApplication) -> Bool {
    guard
      let app = NSRunningApplication(processIdentifier: target.processIdentifier)
    else {
      return false
    }
    // macOS 14+: activate() already brings the app forward; the old
    // activateIgnoringOtherApps option is a no-op / deprecated.
    return app.activate()
  }

  private func captureClipboard() -> ClipboardSnapshot {
    let items = (NSPasteboard.general.pasteboardItems ?? []).map { item in
      [NSPasteboard.PasteboardType: Data](
        uniqueKeysWithValues: item.types.compactMap { type in
          guard let data = item.data(forType: type) else { return nil }
          return (type, data)
        }
      )
    }
    return ClipboardSnapshot(items: items)
  }

  private func preparePasteboard(text: String, marker: String) -> Bool {
    let pasteboard = NSPasteboard.general
    pasteboard.clearContents()
    guard pasteboard.setString(text, forType: .string) else { return false }
    _ = pasteboard.setString(marker, forType: markerType)
    for type in concealmentTypes {
      _ = pasteboard.setString("", forType: type)
    }
    return true
  }

  private func restoreClipboard(_ snapshot: ClipboardSnapshot) {
    let pasteboard = NSPasteboard.general
    pasteboard.clearContents()
    guard !snapshot.items.isEmpty else { return }

    let restoredItems = snapshot.items.map { captured in
      let item = NSPasteboardItem()
      for (type, data) in captured {
        item.setData(data, forType: type)
      }
      return item
    }
    pasteboard.writeObjects(restoredItems)
  }

  /// Insert by replacing the current selection / empty selection (Hex).
  private func insertTextViaAccessibility(_ text: String) -> Bool {
    guard AXIsProcessTrusted() else { return false }

    let systemWide = AXUIElementCreateSystemWide()
    var focusedObject: CFTypeRef?
    guard
      AXUIElementCopyAttributeValue(
        systemWide,
        kAXFocusedUIElementAttribute as CFString,
        &focusedObject
      ) == .success,
      let focusedObject
    else {
      return false
    }

    let focused = focusedObject as! AXUIElement

    // Prefer selected-text replace (works for many AppKit / Electron fields).
    if AXUIElementSetAttributeValue(
      focused,
      kAXSelectedTextAttribute as CFString,
      text as CFTypeRef
    ) == .success {
      return true
    }

    // Fall back to setting the whole value when the control allows it.
    var settable = DarwinBoolean(false)
    if AXUIElementIsAttributeSettable(
      focused,
      kAXValueAttribute as CFString,
      &settable
    ) == .success, settable.boolValue {
      var currentObject: CFTypeRef?
      let current =
        AXUIElementCopyAttributeValue(
          focused,
          kAXValueAttribute as CFString,
          &currentObject
        ) == .success
        ? (currentObject as? String) ?? ""
        : ""
      let combined = current + text
      return AXUIElementSetAttributeValue(
        focused,
        kAXValueAttribute as CFString,
        combined as CFTypeRef
      ) == .success
    }

    return false
  }

  /// Cmd+V via CGEvent. Uses physical V key code 9 so QWERTY-⌘ layouts work
  /// (VoiceInk). Small gaps between events match VoiceInk's CursorPaster.
  private func postPasteShortcut() async -> Bool {
    guard AXIsProcessTrusted() else { return false }

    let source = CGEventSource(stateID: .combinedSessionState)
    let commandKeyCode: CGKeyCode = 0x37  // Left ⌘
    let vKeyCode: CGKeyCode = 0x09  // Physical V

    guard
      let cmdDown = CGEvent(
        keyboardEventSource: source,
        virtualKey: commandKeyCode,
        keyDown: true
      ),
      let vDown = CGEvent(
        keyboardEventSource: source,
        virtualKey: vKeyCode,
        keyDown: true
      ),
      let vUp = CGEvent(
        keyboardEventSource: source,
        virtualKey: vKeyCode,
        keyDown: false
      ),
      let cmdUp = CGEvent(
        keyboardEventSource: source,
        virtualKey: commandKeyCode,
        keyDown: false
      )
    else {
      return false
    }

    cmdDown.flags = .maskCommand
    vDown.flags = .maskCommand
    vUp.flags = .maskCommand

    cmdDown.post(tap: .cghidEventTap)
    try? await Task.sleep(nanoseconds: 12_000_000)
    vDown.post(tap: .cghidEventTap)
    try? await Task.sleep(nanoseconds: 12_000_000)
    vUp.post(tap: .cghidEventTap)
    try? await Task.sleep(nanoseconds: 12_000_000)
    cmdUp.post(tap: .cghidEventTap)
    return true
  }

  /// System Events key code 9 + ⌘ — layout-safe (VoiceInk AppleScript path).
  private func pasteViaAppleScriptKeyCode() -> Bool {
    let source = """
      tell application "System Events" to key code 9 using command down
      """
    var error: NSDictionary?
    guard let script = NSAppleScript(source: source) else { return false }
    script.executeAndReturnError(&error)
    return error == nil
  }

  /// Click Edit → Paste in the frontmost process (Hex menu fallback).
  private func pasteViaEditMenu() -> Bool {
    let source = """
      tell application "System Events"
        tell (first process whose frontmost is true)
          try
            click menu item "Paste" of menu "Edit" of menu bar 1
            return true
          on error
            return false
          end try
        end tell
      end tell
      """
    var error: NSDictionary?
    guard let script = NSAppleScript(source: source) else { return false }
    let result = script.executeAndReturnError(&error)
    return error == nil && result.booleanValue
  }
}
